### ISSUE TITLE
Default `repo`

### ISSUE THREAD

**Issue by gigabo** [lerna/lerna-changelog#1]
Auto-detect from `git remote -v`?

Suggested by @hzoo.

**Comment by gigabo** [comment]
Might be easier to reliably grab the right repo from `package.json`.

Can normalize with [normalize-package-json](https://www.npmjs.com/package/normalize-package-data).

**Comment by hzoo** [comment]
@Turbo87 if you want to take this one too (this config shouldn't be necessary to specifiy) `repo: "babel/babel"`

**Comment by hzoo** [comment]
btw we are on slack too https://lernajs.io/ (or just in the babel one)

**Comment by hzoo** [comment]
yeah we should do this
