### ISSUE TITLE
Remove trailing whitespace from output when there are no changes

### ISSUE THREAD

**Issue by inakianduaga** [lerna/lerna-changelog#118]
Currently, if there are no labeled PRs since the last commit, `lerna-changelog` will output 3 lines of whitespace

```bash
➜  as24-custom-events git:(changelog_generation) ✗ npx lerna-changelog


➜  as24-custom-events git:(changelog_generation) ✗
```

this makes it annoying when we want to automate updating the CHANGELOG automatically via CI because the file will grow even if there are no changes. Should be simple enough to run a `.trim` to the output

**Comment by Turbo87** [comment]
pull requests welcome 😉
