### ISSUE TITLE
Document monorepo support

### ISSUE THREAD

**Issue by jonaskello** [lerna/lerna-changelog#119]
I was looking for something to handle changelogs in monorepos and I came across this. The description of this repo is:

> PR-based changelog generator with monorepo support

However nowhere in the readme is it described in what way monorepos are supported so I'm not sure why I would use this instead of something else for my monorepos. Perhaps the monorepo support could be described a bit more in the readme?

**Comment by Turbo87** [comment]
basically, if you have a `packages` folder and your projects in subfolders of that folder it will detect it and include the package names in the changelog for the relevant changes.

documentation PRs are always welcome :)

**Comment by jonaskello** [comment]
@Turbo87 Thanks, that makes it more clear. Added it to readme in #120.
