### ISSUE TITLE
Must provide GITHUB_AUTH

### ISSUE THREAD

**Issue by Enngage** [lerna/lerna-changelog#130]
Hi, 

Could anyone let me know how can I configure `GITHUB_AUTH` token? I've been trying various ways, but with no luck.

**Comment by Turbo87** [comment]
I'm assuming you saw https://github.com/lerna/lerna-changelog#github-token? What specific step did not work for you?

**Comment by Enngage** [comment]
Thank you for getting back this quickly. Yeah, the thing is I'm not sure where should I place the:

`export GITHUB_AUTH="..."`

Should I create new file somewhere?

**Comment by Turbo87** [comment]
ah, I see. `GITHUB_AUTH` is an "environment variable". you can find more information on those at e.g. https://en.wikipedia.org/wiki/Environment_variable. how exactly this should be used depends on your operating system. what do you use?

**Comment by Enngage** [comment]
Oh, I'm on Win 10. I'm executing the `script via node.js command prompt`, so that means I have to add the environmental variable to it?

**Comment by Turbo87** [comment]
yeah, exactly. I'm not sure how env vars on Win10 are set, unfortunately, but I'm sure a quick internet search will reveal an answer :)

**Comment by Enngage** [comment]
Okey, sounds good. I'll do some googling about that. Thanks for pointing me in the right direction!

**Comment by Enngage** [comment]
I was able to make it work, though I have one off topic question (that I dont think its worth new issue). When ran `lerna-changelog`, it didn't create `changelog.md` file even though it listed my PR correctly. I can copy & paste the result fine, but I was just wondering if this was expected or not.

**Comment by Turbo87** [comment]
yes, that is the expected behavior currently. it will only output the changelog for the latest release by default, but not for all of the releases, unless you use `--to` and `--from`.
