### ISSUE TITLE
vulnerabilities shown under yarn audit

### ISSUE THREAD

**Issue by trivikr** [lerna/lerna-changelog#138]
audit results attached: [lerna-changelog-audit.log](https://github.com/lerna/lerna-changelog/files/3666155/lerna-changelog-audit.log)

```console
1050 vulnerabilities found - Packages audited: 24588
Severity: 403 Low | 10 Moderate | 636 High | 1 Critical
```

**Comment by Turbo87** [comment]
and how many of them are actually relevant to this application?

**Comment by trivikr** [comment]
Almost all of them are related to jest and ts-jest
I tried to update jest in private branch [`upgrade-jest`](https://github.com/trivikr/lerna-changelog/tree/upgrade-jest), but came across some errors.

**Comment by trivikr** [comment]
All these vulnerabilities are fixed if I delete yarn.lock and recreate a new one.
I can do that after #145 lands
