### ISSUE TITLE
Invalid output when using range tags

### ISSUE THREAD

**Issue by hzoo** [lerna/lerna-changelog#35]
This is from running changelog on https://github.com/lerna/lerna

`lerna-changelog --tag-from v2.0.0-beta.32 --tag-to v2.0.0-beta.34`

https://gist.github.com/hzoo/d9eb42b94824694b79be925f357549eb

**Comment by emmenko** [comment]
What exactly am I looking at here? Can you point out the issues you see? Thanks 😉

**Comment by hzoo** [comment]
So I think I would expect the changelog to have 3 entries?

first issue is the first entry is `v2.0.0-beta.3 (2017-01-26)` - missing a 2?

Also I'd think the order would be 32, 33, 34 or 34,33,32

and lastly the commits don't seem to correspond to the commits in the repo?

https://github.com/lerna/lerna/commits/master

**Comment by emmenko** [comment]
I'll have a look into it as soon as I have some time.

**Comment by hzoo** [comment]
## Run
```sh
git clone git@github.com:babel/babylon.git
lerna-changelog --tag-from=v7.0.0-beta.9 --tag-to=v7.0.0-beta.10
```

```
## v7.0.0-beta.1 (2017-05-22)

#### :bug: Bug Fix
* Other
  * [#478](https://github.com/babel/babylon/pull/478) Fixed disappearing comments following a trailing comma. ([@aardito2](https://github.com/aardito2))

#### Committers: 1
- [aardito2](https://github.com/aardito2)


## v7.0.0-beta.10 (2017-05-22)

#### :bug: Bug Fix
* Other
  * [#478](https://github.com/babel/babylon/pull/478) Fixed disappearing comments following a trailing comma. ([@aardito2](https://github.com/aardito2))

#### Committers: 1
- [aardito2](https://github.com/aardito2)
```

**Comment by Turbo87** [comment]
@hzoo the problem is that we are using `indexOf()` to figure out what tag a commit belongs too and `v7.0.0-beta.1` is obviously matching `v7.0.0-beta.10` too 😉
