### ISSUE TITLE
lerna-changelog as part of lerna publish

### ISSUE THREAD

**Issue by DxCx** [lerna/lerna-changelog#46]
Hey,

Is there any best practice for how to integrate both?
atm, lerna-changelog only spits to screen the unreleased changes,
but i want it to actually update CHANGELOG.md automatically when i use lerna publish..

**Comment by alex-pex** [comment]
lerna-changelog can be used during publish, if you launch the command on `version` hook, which is run after version bumping but before the final commit.
```
"version": "lerna-changelog --from v1.0.0 > CHANGELOG.md && git add CHANGELOG.md"
```

The problem is: the new PR are still in an "Unreleased" group. If it anoys you, check my PR: https://github.com/lerna/lerna-changelog/pull/117
```
"version": "lerna-changelog --next-version --from v1.0.0 > CHANGELOG.md && git add CHANGELOG.md"
```

**Comment by evocateur** [comment]
The `--conventional-commits` option of `lerna publish` does 85% of what you’re asking for.

**Comment by alex-pex** [comment]
@evocateur lerna-changelog works using pull requests, convential-commits using … commits! It's two different tools

**Comment by evocateur** [comment]
Well, sure. There are a lot more requirements for `lerna-changelog` (a github token, for starters) that I'd rather not encumber lerna with. Running during the root `version` lifecycle should be more that sufficient to identify the correct version title, as all the version fields have been bumped. (this would require a change to `lerna-changelog`, of course)
