### ISSUE TITLE
`lerna-changelog` doesn't work as expected

### ISSUE THREAD

**Issue by villander** [lerna/lerna-changelog#461]
> By default lerna-changelog will show all pull requests that have been merged since the latest tagged commit in the repository.

After merge a PR with the correct label, the `lerna-changelog` generated a empty changelog. I've been using the last version `1.0.1`. 

```
➜  ember-engines-router-service git:(master) ✗ lerna-changelog


➜  ember-engines-router-service git:(master) ✗ 
```

The public repo: https://github.com/villander/ember-engines-router-service

**Comment by contolini** [comment]
FWIW I see a couple PRs show up when testing locally:

```
~/tmp ✗  node -v
v14.15.4

~/tmp ✗  yarn -v
1.22.5

~/tmp ✗  git clone https://github.com/villander/ember-engines-router-service && cd ember-engines-router-service/

...

~/tmp/ember-engines-router-service master ✗  yarn && yarn changelog

yarn run v1.22.5
$ lerna-changelog

## Unreleased (2021-07-22)

#### :bug: Bug Fix
* [#39](https://github.com/villander/ember-engines-router-service/pull/39) Make transitionTo work with url as an argument ([@SergeAstapov](https://github.com/SergeAstapov))

#### :memo: Documentation
* [#3](https://github.com/villander/ember-engines-router-service/pull/3) Update README ([@jenweber](https://github.com/jenweber))

#### Committers: 3
- Jen Weber ([@jenweber](https://github.com/jenweber))
- Sergey Astapov ([@SergeAstapov](https://github.com/SergeAstapov))
- [@dependabot-preview[bot]](https://github.com/apps/dependabot-preview)
✨  Done in 2.35s.
```

**Comment by iamyoki** [comment]
Me too, don't know how.

**Comment by runspired** [comment]
@villander if this was in a github action, possibly the fetch-depth for the checkout needs to be set to 0?

**Comment by yeshamavani** [comment]
I am facing the same issue as @villander lerna-changelog is empty
Can anyone help me with this

**Comment by Turbo87** [comment]
there is no label on the https://github.com/yeshamavani/release-auto/pull/1 PR

**Comment by yeshamavani** [comment]
@Turbo87 
I am unaware about adding lables to PR how can I do that?

**Comment by yeshamavani** [comment]
hi I got it solved Thanks !!!

**Comment by villander** [comment]
I'm closing it since I got it working from here https://github.com/lerna/lerna-changelog/issues/461#issuecomment-885256340
