### ISSUE TITLE
Sort tags by semver

### ISSUE THREAD

**Issue by Turbo87** [lerna/lerna-changelog#58]
Currently the tags seem to rely on `Object.keys()` sorting behavior... 🤔

**Comment by evocateur** [comment]
```sh
$ git tag --list
v1.1.0
v1.10.0
v1.2.0

$ git tag --list --sort=version:refname
v1.1.0
v1.2.0
v1.10.0

```
https://www.kernel.org/pub/software/scm/git/docs/git-tag.html

**Comment by Turbo87** [comment]
it looks like the original issue was solved by https://github.com/lerna/lerna-changelog/pull/107
