### ISSUE TITLE
Add option to print last version changes

### ISSUE THREAD

**Issue by t-kelly** [lerna/lerna-changelog#76]
It's currently possible to get all the changes since the last release by running `lerna-changelog` before you publish a new release. This spits out a list of changes with a `## Unreleased (2016-05-24)` title.

It would be great to have similar behaviour made available after you publish a new release, so that instead of `## Unreleased (2016-05-24)` you get `## v1.2.3 (2016-05-24)`. 

I realize this is currently possible with the `--tag-from` and `--tag-to` options, e.g. `lerna-changelog --tag-from=v1.2.2 --tag-to=v1.2.3`, but you need to specify tags explicitly. 

It would be great to have a flag like `--tag-latest` that spits out the last release changes.

**Comment by cmdcolin** [comment]
What is the way that people generate changelogs if they do not have this feature?

Do they manually run lerna-changelog --tag-from... --tag-to after doing a release?
