### ISSUE TITLE
Support scoped packages

### ISSUE THREAD

**Issue by Turbo87** [lerna/lerna-changelog#78]
In https://github.com/glimmerjs/glimmer.js we have

```
/
+- packages
   +- @glimmer
      +- foo
      +- bar
      +- baz
```

but the package names are all resolved as `@glimmer` instead of using the full package name.

We should either look at the individual `package.json` files or have a special code path if the first character of the subfolder of `packages` is an `@`.

**Comment by evocateur** [comment]
Why the extra level? This layout works perfectly fine for scoped packages:
```
packages/
  +- foo
  +- bar
  +- baz
```

The content of a given package.json's `name` field is utterly unrelated (for better or worse) to the directory name.

**Comment by hzoo** [comment]
https://github.com/babel/babel/pull/6495 (just did this 😄 )

Yeah you shouldn't need another folder

**Comment by Turbo87** [comment]
Well it wasn't my decision and I just stumbled into the project. Surprisingly it isn't actually using lerna yet, but I still think the changelog gen should work as expected despite the nested folders
