### ISSUE TITLE
Marking changes as “Unreleased” when tag has been pushed already

### ISSUE THREAD

**Issue by tusbar** [lerna/lerna-changelog#84]
I’m trying to generate changelogs and GitHub releases directly from CircleCI when a tag is pushed, but I’m seeing an issue as the changes for the specified range (`--tag-from <previous tag>` `--tag-to <tag that was just pushed>`) are being marked as “Unreleased”

Here’s the generation task on CircleCI: https://circleci.com/gh/tusbar/circleci-samples/154

Basically it is running

```bash
node_modules/.bin/lerna-changelog --tag-from v1.2.3 --tag-to v1.3.0 > CHANGELOG.md
```

And the changelog contains

```markdown
## Unreleased (2017-10-25)

#### :rocket: Enhancement
* [#7](https://github.com/tusbar/circleci-samples/pull/7) Use git-describe to find previous tag. ([@tusbar](https://github.com/tusbar))

#### Committers: 1
- Bertrand Marron ([tusbar](https://github.com/tusbar))
```

Which is weird as the CircleCI task is triggered just when the tag is pushed to the GitHub repository.

What’s even more weird is that if I run that exact command locally at the same time, I get a valid changelog (with the tag name – v1.3.0 – and not “Unreleased”).

Would you happen to know what’s going on here?
I’m using the same GiHub access token on CircleCI and locally…

Thanks for any help.

The full repo is here: https://github.com/tusbar/circleci-samples

**Comment by farism** [comment]
@tusbar I'm not sure we encountered the same problem, but for us it was a git version issue. 

`lerna-changelog` uses a git command `git log --oneline --pretty="%h;%D;%s;%cd" --date=short` to get the list of commits. This ends up breaking on circle because of the `%D` pretty option.
d
The CircleCI image we were using has `git --version` at `2.1.4`. 

The `%D` pretty format option was not added until `2.2.0`

**Comment by tusbar** [comment]
I see, their images are based off jessie. Nice catch, thanks @farism.

**Comment by tusbar** [comment]
Alright, this can easily be fixed by using the `stretch` CircleCI tagged images: https://github.com/tusbar/circleci-samples/pull/12/files.
