### ISSUE TITLE
The 'repo' field automatically inferred failed, but no error occurred

### ISSUE THREAD

**Issue by ayqy** [lerna/lerna-changelog#89]
Refer to Configuration section:

>  `repo`: Your "org/repo" on GitHub (automatically inferred)

I didn't specify a 'repo' field, then ran global installed `lerna-changelog`, and nothing happened, no CHANGELOG or ERROR

Dived into source and got a 'https://api.github.com/repos/undefined/issues/2'. Set a 'repo' field then it works well.

So, an ERROR message is required as it can't be inferred automatically.

**Comment by ayqy** [comment]
$ lerna-changelog --version
0.7.0

**Comment by Turbo87** [comment]
Should be resolved by #102
